spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9jl1hu574zl788iwo.mysql.rds.aliyuncs.com/xiaoshan
    username: suep
    password: Suepsuep1

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB
server:
  port: 8020
  servlet:
    context-path: /stategrid
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

