spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: rm-wz9jl1hu574zl788iwo.mysql.rds.aliyuncs.com
    username: suep
    password: Suepsuep1

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB
server:
  port: 8080